# ===============================
# = DATA SOURCE
# ===============================
# Connection url for the database
spring:
  datasource:
    classname: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/wheelsup
    username: 'wheelsupuser'
    password: 'WHEELSUP@!!2013'
    # Keep the connection alive if idle for a long time (needed in production)
    testWhileIdle: true
    validationQuery: SELECT 1

  # ===============================
  # = JPA / HIBERNATE
  # ===============================
  # Use spring.jpa.properties.* for Hibernate native properties (the prefix is
  # stripped before adding them to the entity manager).

  # Show or not log for each sql query
  jpa:
    show-sql: false
    # Hibernate ddl auto (create, create-drop, update): with "update" the database
    # schema will be automatically updated accordingly to java detail found in
    # the project
    hibernate:
      ddl-auto: none
      dialect: org.hibernate.dialect.MySQL5Dialect
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        cache:
          use_second_level_cache: false
          use_query_cache: false
          region:
            factory_class: org.hibernate.cache.ehcache.EhCacheRegionFactory

